### ISSUE TITLE
使用agile_button库 多次按下案件后提示栈溢出

### ISSUE THREAD

**Issue by arilink-tech** [loogg/agile_button#2]
我使用agile_button库来获取一个按键的状态，当我多次按下按键后 提示栈溢出 系统卡死 感觉像是没有释放的问题 请问该如何解决
？
![image](https://user-images.githubusercontent.com/30901123/120657852-7707ef00-c4b7-11eb-92be-57d5cf50954b.png)

**Comment by loogg** [comment]
menuconfig 将线程堆栈放大
